mod day1;

fn main() -> Result<(), std::io::Error> {
    day1::challenge()
}
